### PR TITLE
106 implement wildcard

### LINKED ISSUE #106: Implement Wildcard

### PR DESCRIPTION
**Pull request by alex216**
fix #106 

## Summary by CodeRabbit

- **New Features**
	- Introduced new functions for expanding variables, quotes, and wildcards in linked lists, enhancing the expansion functionality.
	- Added wildcard expansion capabilities to match filenames using wildcard expressions.

- **Bug Fixes**
	- Improved memory management for environment variable removal.

- **Tests**
	- Implemented comprehensive unit tests for the new expansion features, covering various scenarios for variable and wildcard expansions, including a new test class for wildcard functionality.

### CODE REVIEW

**Comment by alex216** [comment]
I am mad.

**Comment by alex216** [comment]
- [ ] consider IFS in variable, new `expand_variable()` need to return `t_list **`
- [ ] change `expand()` to return `t_list *`, takes `t_list *`
- [ ] remain original `expand_variable()`

**Review by rask24 — COMMENTED** [review]
@alex216 please check the comments.

**Review by rask24 — APPROVED** [review]
@alex216 LGTM 🐷

**Pull request merged**
